# ============ Workflow Configuration ============
#
# general: this section describes the workflow general settings
#   name: the given workflow name
#   samples_per_batch: number of samples in a workflow batch
#   default_batch_input_location: default navigation graph location where a batch is added
#                                 where node_id stands for the node number in the navigation
# 
general:
  name: weighing_test_workflow
  samples_per_batch: 1
  default_batch_input_location:
    node_id: 25
    graph_id: 1

# robots: this section describes the robots used in the workflow
#   type: the robot's class name as defined in archemist.robots.X.state 
#         note that X stands for the robot's given module found in archemist's robots 
#         module
#   id: the robot unique workflow id
#   batch_capacity: the number of batches the robot can carry/handle at a time
#   handler: robot handler class name as defined in archemist.robots.X.handler
#
# for every robot used in the workflow, add a new entry and fill its fields as defined
#robots:
#  - type: KukaLBRIIWA
#    id: 1
#    batch_capacity: 2
#    handler: KmriiwaROSHandler

# stations: this section describes the stations used in the workflow
#   type: the station's class name as defined in archemist.stations.X.state
#         note that X stands for the stations's given module found in archemist's 
#         stations module
#   id: the station unique workflow id
#   location: station's location in the robot navigation graph where node_id stands for the 
#             node number in the navigation graph whose id is given 
#   batch_capacity: number of batches the station can handle at a time
#   handler: station handler class name as defined in archemist.stations.X.handler
#   parameters: any additional parameters need to be passed to the station when initialized
#   process_state_machine: state machine describing the station process 
#   type: the station process state machine class name as defined in archemist.stations.X.process
#   args: any additional arguments that need to be passed to the state machine constructor
#
# for every station used in the workflow, add a new entry and fill its fields as defined
stations:
  - type: WeighingStation
    id: 11
    location:
      node_id: 25
      graph_id: 1
    batch_capacity: 1
    handler: KernPcbROSHandler
    process_state_machine:
      type: WeighingSM
      args:
    parameters:


