# Available commands to use the MT Quantos System
int32 STARTDOSE = 0
int32 STOPDOSE = 1
int32 GETDOORPOS = 2
int32 GETSAMPLEPOS = 3
int32 GETHEAD = 4
int32 GETSAMPLE = 5
int32 MOVEPIN = 6
int32 MOVEDOOR = 7
int32 SETSAMPLEPOS = 8
int32 SETTAPBEFORE = 9
int32 SETTAPDURING = 10
int32 SETTAPINT = 11
int32 SETTAPDURATION = 12
int32 SETTARGET = 13
int32 SETTOL = 14
int32 SETTOLMODE = 15
int32 SETSAMPLEID = 16
int32 SETPANOFF = 17
int32 SETALGO = 18
int32 SETAS = 19
int32 DISPENSESOLID = 20

int32 quantos_command
string quantos_ID
bool quantos_bool
float32 quantos_float
int32 quantos_int
