# ============ Workflow Configuration ============
#
# general: this section describes the workflow general settings
#   name: the given workflow name

general:
  name: apc_workflow

# ============ Workflow Input Configuration ============
#
# workflow_input: this section describes the workflow lot input settings
#   location: location of the input site
#   samples_per_batch: number of samples in a single batch
#   batches_per_lot: number of batch in a single lot
#   total_lot_capacity: maximum number of lot that can be stored 
#                       at the input site
#   lot_input_process: define the process used to input lots into the workflow
#     type: the process's class name as defined in archemist.processes.X
#         note that X stands for the process's given module found in archemist's 
#         processes module
#     args: arguments to construct the lot input process if needed

workflow_input:
  location:
    coordinates: [1,1]
    descriptor: input_site
  samples_per_batch: 2
  batches_per_lot: 1
  total_lot_capacity: 1
  lot_input_process: Null

# ============ Workflow Output Configuration ============
#
# workflow_output: this section describes the workflow lot output settings
#   location: location of the output site
#   total_lot_capacity: maximum number of lot that can be stored 
#                       at the output site
#   lots_need_manual_removal: specify whether the lots need to be manually removed
#                             from the output site
#   lot_output_process: define the process used to output lots into the workflow
#     type: the process's class name as defined in archemist.processes.X
#         note that X stands for the process's given module found in archemist's 
#         processes module
#     args: arguments to construct the lot output process if needed

workflow_output:
  location:
    coordinates: [1,1]
    descriptor: output_site
  total_lot_capacity: 1
  lots_need_manual_removal: False
  lot_output_process: Null

# robots: this section describes the robots used in the workflow
#   type: the robot's class name as defined in archemist.robots.X.state 
#         note that X stands for the robot's given module found in archemist's robots 
#         module
#   id: the robot unique workflow id
#   handler: robot handler class name as defined in archemist.robots.X.handler
#   total_lot_capacity: the max number of lots the robot can carry/handle at a time
#                       only needed if robot of type MobileRobot
#   onboard_capacity: the max number of batches the robot can carry/handle at a time
#                       only needed if robot of type MobileRobot
#   location: location of the robot if available
#
# for every robot used in the workflow, add a new entry and fill its fields as defined

robots:
  - type: KMRIIWARobot
    id: 2
    handler: KmriiwaROSHandler
    total_lot_capacity: 1
    onboard_capacity: 1

# stations: this section describes the stations used in the workflow
#   type: the station's class name as defined in archemist.stations.X.state
#         note that X stands for the stations's given module found in archemist's 
#         stations module
#   id: the station unique workflow id
#   location: station's location defined in terms of x,y coordinates and string descriptor 
#   total_lot_capacity: number of lots the station can handle at a time
#   handler: station handler class name as defined in archemist.stations.X.handler
#   properties: any additional properties need to be passed to the station when initialized
#   materials: this section describes the materials used in the station
#     liquids:
#       name: the liquid name
#       amount: the liquid stored amount
#       unit: measurement unit representing stored amount, accepted units L, mL, uL,m3, cm3, mm3
#       density: liquid density
#       density_unit: measurement unit representing liquid density
#       details: all other liquid details such as its source, colour, etc. 
#       expiry_date: expiry date of the liquid
#     solids:
#       name: the solid name
#       amount: the solid stored amount
#       unit: the unit representing stored amount, accepted units g, mg, ug, kg
#       details: all other solid details such as its source, colour, etc.
#       expiry_date: expiry date of the solid
#
# for every station used in the workflow, add a new entry and fill its fields as defined

stations:
  - type: SyringePumpStation
    id: 1
    location:
      coordinates: [1,1]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: APCSyringePumpStationRosHandler
    properties: Null
    materials:
      liquids:
        - name: acetic_anhydride
          amount: 2000
          unit: mL
          density: 1000
          density_unit: kg/m3
          details:
            inlet_port: 1
            outlet_port: 2
          expiry_date: 31/03/2024
        - name: water
          amount: 100000
          unit: mL
          density: 1000
          density_unit: kg/m3
          details:
            inlet_port: 3
            outlet_port: 4
          expiry_date: 31/03/2024
  - type: DiaphragmPumpStation
    id: 2
    location:
      coordinates: [1,1]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimDiaphragmPumpStationHandler
    properties: Null
    materials:
      liquids:
        - name: water
          amount: 100000
          unit: mL
          density: 1000
          density_unit: kg/m3
          details: Null
          expiry_date: 31/03/2024
  - type: APCFumehoodStation
    id: 3
    location:
      coordinates: [36,8]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: APCFumeHoodStationRosHandler
    properties:
      cartridges:
        - associated_solid: 4-aminophenol
          hotel_index: 1
        - associated_solid: 4-aminophenol
          hotel_index: 2
    materials:
      solids:
        - name: 4-aminophenol
          amount: 10000
          unit: g
          expiry_date: 31/03/2024
          details: Null
  - type: MTSynthesisStation
    id: 4
    location:
      coordinates: [36,8]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: APCMTSynthesisStationRosHandler  
    materials: Null
    properties:
      num_sampling_vials: 12
  - type: APCFiltrationStation
    id: 5
    location:
      coordinates: [34,8]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: APCFiltrationStationHandler
    materials: Null
    properties: Null
  - type: WatersLCMSStation
    id: 6
    location:
      coordinates: [35,8]
      descriptor: lcms_station
    total_lot_capacity: 1
    handler: WaterLCMSRosHandler
    materials: Null
    properties: Null
  - type: APCWeighingStation
    id: 7
    location:
      coordinates: [34,8]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: APCWeighingStationHandler
    properties:
      funnel_storage_capacity: 3
    materials: Null
  - type: APCMetaStation
    id: 8
    location:
      coordinates: [1,1]
      descriptor: apc_fumehood
    total_lot_capacity: 1
    handler: SimStationOpHandler
    materials: Null
    properties: Null
